apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: test-sealed
  namespace: {{ .Values.namespace }}
spec:
  encryptedData:
      {{- toYaml .Values.secret.sealedsecret | nindent 12 }}  template:
    data: null
    metadata:
      creationTimestamp: null
      name: test-sealed
      namespace: {{ .Values.namespace }}
    type: Opaque
