apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: test-sealed
  namespace: {{.Values.namespace}}
spec:
  encryptedData:
     {{- toYaml .Values.secret.sealedsecret | nindent 12 }}
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"    
      creationTimestamp: null
      name: test-sealed
      namespace: {{.Values.namespace}}
    type: Opaque
