apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-service
  namespace: {{.Values.namespace}}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.targetport }}
  selector:
    app: {{ .Values.name }}    
  type:  {{ .Values.service.type }}  
  
