apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
spec:
  generators:
  - git:
      repoURL: https://github.com/mahmoudaboghadeer93/argocd_helm.git
      revision: HEAD
      directories:
      - path: all_ms/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/mahmoudaboghadeer93/argocd_helm.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
      #  namespace: '{{path.basename}}'
        namespace: qa