name: myapp-first
replicaCount: 1
namespace: test2

image:
  repository: nanajanashia/argocd-app
  pullPolicy: Always
  tag: "1.2"

podSecurityContext: {}

service:
  type: ClusterIP
  port: 8080
  targetport: 8080

container:
  port: 8080
secret:
  sealedsecret: 
     password: AgCkHX9WEU2jfAEiKwG03pbA/MC9SBm4WPUM8NojSmf6H67pRvx4SIuFztM9KM8s2cVMlRI9a9gT/QhDJIJh1r6ulW3t2YT4fUNCG97pSKP+ZQGyWNv8JRYJsZ+Fu/agUrxxw/NwVtJTe+qePqYbxflJSKZ7NbE/U3FMZuRxbTUMuj3dYnoS5bdh0eZzQrFZkfkdSyGZb4kJTDYaeRWeSav+XQXJZx3lpLqY5uf60qw41l+lwU5R1UI8Qbkbrs8zsChw26D9BSUN75mzopDEMMQLxeFjb83SBYE91YOr36dlVEZ2p2UsuZjDwe3UzsitkVmZ87EJy4oE4k8Rauxhry0u+mIr3L67Yye/jiZdBsw+1wNb5dAssjif2oYUN2CXjlzEXCp9JdarqlOccGKpzX0TCgyZLns0cVri61LUxJWSzDbBmBnk8EWIcCrkVBXs+JOna985FMhAyU2fdPwVVI33O/lrXZDx/U9A/kBSBsYl9kYanmG+LuemvTtVp+RbmUiNjqtHeQwAWO0CUpgeVAu/KfIwEYFv2tv4+6OJ9W1cpdXntJfhYjknDTq8c+5OufXJ0u5FWQcz+zsQS9Peef+1LNn5LJPvuNLgJ72Nt7SteIgZcwbNov//rLODKKuiRBnJrWgMtAlxzQfAK/9rnhnsOciFwUz4C39dyJJBX+XXSDKd07YYR7VZUytp99pgQUMjUbMEQGk=
