name: myapp-first
replicaCount: 1
namespace: test2

image:
  repository: nanajanashia/argocd-app
  pullPolicy: Always
  tag: "1.2"

podSecurityContext: {}

service:
  type: ClusterIP
  port: 8080
  targetport: 8080

container:
  port: 8080
secret:
  sealedsecret: 
     password: AgA0YtFPM+HkWlBBnMtWPOYGJSQKNRNYoG8oZZOopJDiyrW4a5C8MJcOgfBHWSDaFAN6mt9BapIUAUw8xiMxNBKEXPg56sND7SaoB8fJcsiHlFm9z5J/0my+CHVOXFX7ewyPr2oTi01EjdRUrBUdtpz4bZdtirbA8np0FK00CLlcAV7jvbjpAQsCgwXdkIOlp0Mkmb3RebVx9ixdgb/Ns0abo4zASIkCU6bsXy0lZDIE1JF+rQ30zl7KvdqGEKEZeJqixpyXb8S2LvJ8meFZM3wlFwXIEdNtM0Bx7/YZwHmNuKcl5L0Z2+z7xsv5s3Hpc98iSsK73S594CoBxrt6tpTnXF7R/La966ahU0yTpOPR2OTqpBLe4Fz9xlv4AuOyAv1vc8DUpt/tEWUzcsGeLrgVgy9waL7dOcqB3kFhabkLhIBb+yMgCRAH24y8oZ4DLQH019qkJEsMuQbbNrTfccVINAVwTuWH1VdEM0HJ//+3TyZSLf354ws545U/hqihovZO0zjF1fPgJCNyau7SApRvZYUZEVFBinrlBCJq7rt/XCr5JmDAU2TTHOJ1wxn6tOt2J9hyptd/2ZEBL6tx0jPTqPSAwzDjtNKSa7sYxnwqgi0/aMbLMGkktA/UtLckzOwaSuhrfiWRnmzxNtwkbPEqxsgNpRpuwOU2NUAdRmVLczxdvZ0M2IhvM5dso5VzMdX3J6G6d+U=
