name: myapp-first
replicaCount: 1
namespace: test2

image:
  repository: nanajanashia/argocd-app
  pullPolicy: Always
  tag: "1.2"

podSecurityContext: {}

service:
  type: ClusterIP
  port: 8080
  targetport: 8080

container:
  port: 8080
secret:
  sealedsecret: 
    password: AgCP307KroTMH5Z/IVpq0YbVSdZb2ex5U1oymKh05+PigFRAv17wKXtKuzCsdIohxpCnO1n08b1wZ6XoD8HJ/CC0tmnd3V74mlQS9gbowMOqC2R+c2xSxKFE8pnXglqIjhvQfswlbT04SXyfOhtVu/3cOSlt7mohvSAKLFYdWpK6woyeKoLJa7hZ4SbBeR1sJOtkqVXOJkyswLdELM0q6P3nlu9YGV9d9MAGw3BXvhxEq5dV2az9Hl+F7QRdWFH83b3kUmnwixf6SCL5ORAPwTyVD8UlendyatCb7uPj1jD9PRUEk0KekO7WZQ6faQQpwDDadUdUoum/y7AmU3UDv5uk9tgU8yF4//G2EoAdaOvEZ5J7/hiAJGJNmr7pnJLRiWwZtT0L7hrxV6Q2J4Dy2kL+ASlBP7whGbd4AMRRHQzVzigsF+CtdAcyrQ7ODUVHBRYs/HVJ8PWHxBJmJYfzXi9856KPUUAxDIJCg/Y+0f5msM3Jl85xETMgyHnCgPnAc4n8OmLnn/8P88kRSYbCjn/DW36j++27PDjoKpupnBxdeD1jXxKxeNm8+fuaA5PRcLXqMIKYWeCO4IinRIhOGC529xtYeOsSQOjkWCjCQquC+jPdrDaAPe9OGZhpIWznFM0jmpMjN509hvRDvmIorbXQJa2VDluX0PYCBCo1r36uoCwUKSqr6Amq3fbWzT3tyWbyjhLBca8=
