name: myapp-first
replicaCount: 1
namespace: test2

image:
  repository: nanajanashia/argocd-app
  pullPolicy: Always
  tag: "1.2"

podSecurityContext: {}

service:
  type: ClusterIP
  port: 8080
  targetport: 8080

container:
  port: 8080
secret:
  sealedsecret: 
     password: AgAt3nkMCV31Pj8QD3YiP+VNwUjv/xXpBgHsyWrdoJwIXLyKDrohCgf046hwlP7pEn+w1uKM5ObvISFzekV21oh6J4qZSBEcHgn9xGk/HBcZc+LJtId5iiKn/newfesJbphhbds1ffubqlwXOpBRNS8qGP/FQU6p6ZN3BWvGUx63AycBE5Cu3Wis2xIvODLU6C+zhOLPB1mwurtJc8nmflaLWs0TRdohaCb9aaIB9PuoJOQRgqNsOsPamvn1iUjnjcaOR+VWijqa9PW6Qqc8cLBVAj9ekvl3FaSH4TBeG/iCnf6wyPh83BYrYxbTfX8zZA7s9m5QlxCZTYx5AMReh9gv1W+XjjaPaKN298mWCi0KH8GvjI5ne/eq6gltz+yDj7+rX25MqEba9P9xcE0P+mN1bgUaiLr+DPiPJMLtMA0RdYMs72lf88Ry6zaltYR8wJv5il6X8t57LGu034a3yca8sX4WOUby9mIO5CRMTzEOSyhc4e2k1rvxPNocsxagSXu/yIT4w0hepRRpywaD8hl1QBPtG7M5n6rjRG5Cto1nFkP7AQUjA/YcfLe5aO8TC0FSYoLrpfRnk330nIGcggGO7LqYtrwURemn8YrJtzH+3a/PjqEyvbIJa4SxbEglLKcwdfvyUbLdEU2pw3I8IvrWnPOb1YmoICdZDKVQybNyCtVgs/AJ2sq9iIYrFXVA/wvRqKSJYDw=
