name: myapp-first
replicaCount: 0

image:
  repository: nanajanashia/argocd-app
  pullPolicy: Always
  tag: "1.2"

podSecurityContext: {}

service:
  type: ClusterIP
  port: 8080
  targetport: 8080

container:
  port: 8080

